### ISSUE TITLE
Editing metadata of resource changes the resource url to ___

### ISSUE THREAD

**Issue by ismail-shahzad** [datopian/ckanext-cloudstorage#2]
Whenever we change the metadata for the resource by editing it the URL is changed to `___`

## Acceptance
* [x] URL generated for the resource is correct

## Tasks
* [x] Debug and fix

## Steps to replicate the issue
* Create a resource
* Edit the newly created resource
* Change only one field and press update
* The URL should be different now (wrong one i.e. `___`)

**Comment by osahon-okungbowa** [comment]
closing this has been addressed in https://github.com/datopian/ckanext-cloudstorage/issues/3
